#
# 本地集成测试环境的配置文件。
#
# 由于本文件放在config目录下，因此将覆盖fgj-web的设置
#

# 文件根目录
fileroot: ${user-home}/fgj/dev

redis-host: www.jkjsf.net
qis-server: http://www.jkjsf.net
hec-server: http://www.jkjsf.net/hec-web

server:
    port: 8080
    contextPath: /fgj

spring.datasource:
    url: jdbc:h2:tcp://localhost/~/h2/fgjit;MODE=Oracle
    username: sa
    password:
